name: Run CI to see if it works
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: false
          lfs: false
      - name: Get Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Build source files
        shell: bash
        run: |
          yarn
          yarn gulp deploy
