name: Deploy new production version (production)
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: false
          lfs: false
      - name: Get Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Build source files
        shell: bash
        run: |
          yarn
          yarn gulp deploy
      - name: Deploy trunk to SVN
        env:
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
          SLACK_HOOKURL: ${{ secrets.SLACK_HOOKURL }}
        run: |
          $GITHUB_WORKSPACE/scripts/github-deploy.sh
